# Generated by Django 4.0.5 on 2022-07-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
    ]
